// @generated by AI Unit Test Agent -- review before merging
import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
import CreateProductForm from './CreateProductForm';
import { useProductStore } from '../stores/useProductStore';

jest.mock('../stores/useProductStore', () => ({
  useProductStore: jest.fn(),
}));

jest.mock('framer-motion', () => {
  const React = require('react');
  return {
    motion: new Proxy(
      {},
      {
        get: (_t, tag) => ({ children, initial, animate, transition, ...rest }) =>
          React.createElement(tag, rest, children),
      }
    ),
    AnimatePresence: ({ children }) => children,
  };
});

const IMAGE_DATA = 'data:image/png;base64,STUBBED';

describe('CreateProductForm', () => {
  let createProduct;
  const originalFileReader = global.FileReader;
  let readAsDataURL;

  beforeEach(() => {
    createProduct = jest.fn().mockResolvedValue(undefined);
    useProductStore.mockReturnValue({ createProduct, loading: false });

    readAsDataURL = jest.fn();
    global.FileReader = class {
      constructor() {
        this.result = null;
        this.onloadend = null;
      }
      readAsDataURL(file) {
        readAsDataURL(file);
        this.result = IMAGE_DATA;
        if (this.onloadend) this.onloadend();
      }
    };
  });

  afterEach(() => {
    global.FileReader = originalFileReader;
    jest.restoreAllMocks();
    jest.clearAllMocks();
  });

  const fillForm = async (user) => {
    await user.type(screen.getByLabelText('Product Name'), 'Blue Jeans');
    await user.type(screen.getByLabelText('Description'), 'Nice denim');
    await user.type(screen.getByLabelText('Price'), '19.99');
    await user.selectOptions(screen.getByLabelText('Category'), 'jeans');
  };

  it('should render heading, all fields and the submit button', () => {
    render(<CreateProductForm />);
    expect(screen.getByRole('heading', { name: 'Create New Product' })).toBeInTheDocument();
    expect(screen.getByLabelText('Product Name')).toBeInTheDocument();
    expect(screen.getByLabelText('Description')).toBeInTheDocument();
    expect(screen.getByLabelText('Price')).toBeInTheDocument();
    expect(screen.getByLabelText('Category')).toBeInTheDocument();
    expect(screen.getByLabelText('Upload Image')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /create product/i })).toBeInTheDocument();
  });

  it('should render the category select with placeholder and all seven categories', () => {
    render(<CreateProductForm />);
    const select = screen.getByLabelText('Category');
    const options = Array.from(select.querySelectorAll('option')).map((o) => o.textContent);
    expect(options).toEqual([
      'Select a category',
      'jeans',
      't-shirts',
      'shoes',
      'glasses',
      'jackets',
      'suits',
      'bags',
    ]);
    expect(select).toHaveValue('');
  });

  it('should update controlled fields as the user types and selects', async () => {
    const user = userEvent.setup();
    render(<CreateProductForm />);
    await fillForm(user);
    expect(screen.getByLabelText('Product Name')).toHaveValue('Blue Jeans');
    expect(screen.getByLabelText('Description')).toHaveValue('Nice denim');
    expect(screen.getByLabelText('Price')).toHaveValue(19.99);
    expect(screen.getByLabelText('Category')).toHaveValue('jeans');
  });

  it('should call createProduct with the entered data on submit', async () => {
    const user = userEvent.setup();
    render(<CreateProductForm />);
    await fillForm(user);
    await user.click(screen.getByRole('button', { name: /create product/i }));
    await waitFor(() => expect(createProduct).toHaveBeenCalledTimes(1));
    expect(createProduct).toHaveBeenCalledWith({
      name: 'Blue Jeans',
      description: 'Nice denim',
      price: '19.99',
      category: 'jeans',
      image: '',
    });
  });

  it('should reset all fields after successful submission', async () => {
    const user = userEvent.setup();
    render(<CreateProductForm />);
    await fillForm(user);
    await user.click(screen.getByRole('button', { name: /create product/i }));
    await waitFor(() => expect(screen.getByLabelText('Product Name')).toHaveValue(''));
    expect(screen.getByLabelText('Description')).toHaveValue('');
    expect(screen.getByLabelText('Price')).toHaveValue(null);
    expect(screen.getByLabelText('Category')).toHaveValue('');
  });

  it('should prevent default form submission', async () => {
    const { container } = render(<CreateProductForm />);
    const form = container.querySelector('form');
    const notPrevented = fireEvent.submit(form);
    expect(notPrevented).toBe(false);
    await waitFor(() => expect(createProduct).toHaveBeenCalledTimes(1));
  });

  it('should read selected image file as data URL and show Image uploaded', async () => {
    const user = userEvent.setup();
    render(<CreateProductForm />);
    expect(screen.queryByText(/Image uploaded/)).not.toBeInTheDocument();
    const file = new File(['abc'], 'pic.png', { type: 'image/png' });
    await user.upload(screen.getByLabelText('Upload Image'), file);
    expect(readAsDataURL).toHaveBeenCalledWith(file);
    expect(await screen.findByText(/Image uploaded/)).toBeInTheDocument();
  });

  it('should include the base64 image in the submitted product', async () => {
    const user = userEvent.setup();
    render(<CreateProductForm />);
    await fillForm(user);
    const file = new File(['abc'], 'pic.png', { type: 'image/png' });
    await user.upload(screen.getByLabelText('Upload Image'), file);
    await user.click(screen.getByRole('button', { name: /create product/i }));
    await waitFor(() => expect(createProduct).toHaveBeenCalledTimes(1));
    expect(createProduct).toHaveBeenCalledWith(
      expect.objectContaining({ image: IMAGE_DATA, name: 'Blue Jeans' })
    );
  });

  it('should do nothing when the file input change has no file', () => {
    render(<CreateProductForm />);
    const input = document.getElementById('image');
    fireEvent.change(input, { target: { files: [] } });
    expect(readAsDataURL).not.toHaveBeenCalled();
    expect(screen.queryByText(/Image uploaded/)).not.toBeInTheDocument();
  });

  it('should preserve previously typed fields after an image is loaded', async () => {
    const user = userEvent.setup();
    render(<CreateProductForm />);
    await fillForm(user);
    const file = new File(['abc'], 'pic.png', { type: 'image/png' });
    await user.upload(screen.getByLabelText('Upload Image'), file);
    expect(await screen.findByText(/Image uploaded/)).toBeInTheDocument();
    expect(screen.getByLabelText('Product Name')).toHaveValue('Blue Jeans');
    expect(screen.getByLabelText('Description')).toHaveValue('Nice denim');
    expect(screen.getByLabelText('Price')).toHaveValue(19.99);
    expect(screen.getByLabelText('Category')).toHaveValue('jeans');
  });

  it('should show loading state and disable the button when store loading is true', () => {
    useProductStore.mockReturnValue({ createProduct, loading: true });
    render(<CreateProductForm />);
    const button = screen.getByRole('button', { name: /loading/i });
    expect(button).toBeDisabled();
    expect(button).toHaveTextContent('Loading...');
    expect(screen.queryByText('Create Product', { selector: 'button' })).not.toBeInTheDocument();
    expect(button).not.toHaveTextContent('Create Product');
  });

  it('should show enabled Create Product button when not loading', () => {
    render(<CreateProductForm />);
    const button = screen.getByRole('button', { name: /create product/i });
    expect(button).toBeEnabled();
    expect(screen.queryByText(/Loading\.\.\./)).not.toBeInTheDocument();
  });

  it('should not reset the form and should log when createProduct rejects', async () => {
    const user = userEvent.setup();
    const logSpy = jest.spyOn(console, 'log').mockImplementation(() => {});
    createProduct.mockRejectedValue(new Error('fail'));
    render(<CreateProductForm />);
    await fillForm(user);
    await user.click(screen.getByRole('button', { name: /create product/i }));
    await waitFor(() => expect(logSpy).toHaveBeenCalledWith('error creating a product'));
    expect(screen.getByLabelText('Product Name')).toHaveValue('Blue Jeans');
    expect(screen.getByLabelText('Description')).toHaveValue('Nice denim');
    expect(screen.getByLabelText('Price')).toHaveValue(19.99);
    expect(screen.getByLabelText('Category')).toHaveValue('jeans');
  });

  it('should mark name, description, price and category as required and price step as 0.01', () => {
    render(<CreateProductForm />);
    expect(screen.getByLabelText('Product Name')).toBeRequired();
    expect(screen.getByLabelText('Description')).toBeRequired();
    expect(screen.getByLabelText('Price')).toBeRequired();
    expect(screen.getByLabelText('Category')).toBeRequired();
    const price = screen.getByLabelText('Price');
    expect(price).toHaveAttribute('type', 'number');
    expect(price).toHaveAttribute('step', '0.01');
    expect(document.getElementById('image')).toHaveAttribute('accept', 'image/*');
  });
});