// @generated by AI Unit Test Agent -- review before merging
import React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
import toast from 'react-hot-toast';
import ProductCard from './ProductCard';
import { useUserStore } from '../stores/useUserStore';
import { useCartStore } from '../stores/useCartStore';

jest.mock('react-hot-toast', () => ({
  __esModule: true,
  default: { error: jest.fn(), success: jest.fn() },
  toast: { error: jest.fn(), success: jest.fn() },
}));

jest.mock('../stores/useUserStore', () => ({
  useUserStore: jest.fn(),
}));

jest.mock('../stores/useCartStore', () => ({
  useCartStore: jest.fn(),
}));

describe('ProductCard', () => {
  const product = {
    _id: 'p1',
    name: 'Cool Sneakers',
    price: 99,
    image: 'http://example.com/sneakers.png',
  };
  let addToCart;

  beforeEach(() => {
    jest.clearAllMocks();
    addToCart = jest.fn();
    useCartStore.mockReturnValue({ addToCart });
    useUserStore.mockReturnValue({ user: { _id: 'u1', name: 'Bob' } });
  });

  it('should render product name, price with dollar sign and image', () => {
    render(<ProductCard product={product} />);
    expect(screen.getByText('Cool Sneakers')).toBeInTheDocument();
    expect(screen.getByText('$99')).toBeInTheDocument();
    const img = screen.getByAltText('product image');
    expect(img).toHaveAttribute('src', product.image);
  });

  it('should render an Add to cart button', () => {
    render(<ProductCard product={product} />);
    expect(screen.getByRole('button', { name: /add to cart/i })).toBeInTheDocument();
  });

  it('should call addToCart with the product when a logged-in user clicks the button', async () => {
    const user = userEvent.setup();
    render(<ProductCard product={product} />);
    await user.click(screen.getByRole('button', { name: /add to cart/i }));
    expect(addToCart).toHaveBeenCalledTimes(1);
    expect(addToCart).toHaveBeenCalledWith(product);
    expect(toast.error).not.toHaveBeenCalled();
  });

  it('should show a login error toast and not add to cart when user is not logged in', async () => {
    useUserStore.mockReturnValue({ user: null });
    const user = userEvent.setup();
    render(<ProductCard product={product} />);
    await user.click(screen.getByRole('button', { name: /add to cart/i }));
    expect(toast.error).toHaveBeenCalledTimes(1);
    expect(toast.error).toHaveBeenCalledWith('Please login to add products to cart', { id: 'login' });
    expect(addToCart).not.toHaveBeenCalled();
  });

  it('should not call addToCart or toast on initial render without a click', () => {
    render(<ProductCard product={product} />);
    expect(addToCart).not.toHaveBeenCalled();
    expect(toast.error).not.toHaveBeenCalled();
  });

  it('should call addToCart on each click when clicked multiple times while logged in', async () => {
    const user = userEvent.setup();
    render(<ProductCard product={product} />);
    const button = screen.getByRole('button', { name: /add to cart/i });
    await user.click(button);
    await user.click(button);
    expect(addToCart).toHaveBeenCalledTimes(2);
    expect(addToCart).toHaveBeenNthCalledWith(1, product);
    expect(addToCart).toHaveBeenNthCalledWith(2, product);
  });

  it('should render a price of 0 and a long product name without crashing', () => {
    const longName = 'A'.repeat(300);
    const edgeProduct = { ...product, price: 0, name: longName };
    expect(() => render(<ProductCard product={edgeProduct} />)).not.toThrow();
    expect(screen.getByText('$0')).toBeInTheDocument();
    expect(screen.getByText(longName)).toBeInTheDocument();
  });
});